language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:

after_script: 
- gem over bot
script :
  - awesome_bot README.md --allow-dupe --white-list awesome-django,django-pagination,djangobeer,django-dynamic-preferences.,djangovillage
